# Generated by Django 5.0.4 on 2024-05-28 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communicationapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='course',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
