# Generated by Django 5.0.4 on 2024-05-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communicationapp', '0002_remove_announcement_batch_remove_announcement_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
