# Generated by Django 5.0.4 on 2024-06-01 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_student'),
        ('communicationapp', '0004_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='posted_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='adminapp.teacher'),
        ),
    ]
