# Generated by Django 5.0.4 on 2024-06-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communicationapp', '0005_alter_notifications_posted_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
