# Generated by Django 5.0.4 on 2024-06-04 05:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communicationapp', '0006_alter_notifications_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='posted_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
