# Generated by Django 5.0.4 on 2024-06-06 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_country_state_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.city'),
        ),
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.country'),
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.state'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.city'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.country'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.state'),
        ),
    ]
