# Generated by Django 5.0.6 on 2024-06-19 05:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_student_city_student_country_student_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['dob'], name='adminapp_st_dob_242f1b_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['gender'], name='adminapp_st_gender_8e4b77_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['mobile'], name='adminapp_st_mobile_6e1341_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['father_name'], name='adminapp_st_father__f8ade3_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['course'], name='adminapp_st_course__286c70_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['batch'], name='adminapp_st_batch_i_c5a37c_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['country'], name='adminapp_st_country_cc17de_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['state'], name='adminapp_st_state_i_30a398_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['city'], name='adminapp_st_city_id_668dc7_idx'),
        ),
    ]
