# Generated by Django 5.0.6 on 2024-06-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_alter_student_options_alter_student_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mobile',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['name'], name='adminapp_te_name_454df6_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['username'], name='adminapp_te_usernam_fdfc68_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['mobile'], name='adminapp_te_mobile_bb0338_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['email'], name='adminapp_te_email_efe1ac_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['course'], name='adminapp_te_course__021813_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['batch'], name='adminapp_te_batch_i_1e0f1b_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['country'], name='adminapp_te_country_3ba787_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['state'], name='adminapp_te_state_i_880fe4_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['city'], name='adminapp_te_city_id_651fbd_idx'),
        ),
    ]
