# Generated by Django 5.0.6 on 2024-06-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_remove_teacher_adminapp_te_name_454df6_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
