# Generated by Django 5.0.4 on 2024-05-23 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0004_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reportcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark1', models.IntegerField()),
                ('mark2', models.IntegerField()),
                ('mark3', models.IntegerField()),
                ('mark4', models.IntegerField()),
                ('mark5', models.IntegerField()),
                ('stuname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.student')),
                ('sub1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub1', to='certificatereportapp.subject')),
                ('sub2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub2', to='certificatereportapp.subject')),
                ('sub3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub3', to='certificatereportapp.subject')),
                ('sub4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub4', to='certificatereportapp.subject')),
                ('sub5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub5', to='certificatereportapp.subject')),
            ],
        ),
    ]
