# Generated by Django 5.0.4 on 2024-05-21 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_student'),
        ('teacherapp', '0003_remove_coursematerial_uploaded_at_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('morning_attendance', models.BooleanField(default=False)),
                ('afternoon_attendance', models.BooleanField(default=False)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.teacher')),
            ],
        ),
    ]
