# Generated by Django 5.0.4 on 2024-05-21 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_student'),
        ('teacherapp', '0004_teacherattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherattendance',
            name='afternoon_attendance',
        ),
        migrations.RemoveField(
            model_name='teacherattendance',
            name='morning_attendance',
        ),
        migrations.RemoveField(
            model_name='teacherattendance',
            name='teacher',
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='arrival_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='break_end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='break_start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='departure_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='teacher_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.teacher'),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
