# Generated by Django 5.0.4 on 2024-05-21 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0005_remove_teacherattendance_afternoon_attendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherattendance',
            name='remarks',
        ),
    ]
