# Generated by Django 5.0.4 on 2024-05-28 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_student'),
        ('teacherapp', '0006_remove_teacherattendance_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='adminapp.student'),
        ),
    ]
